### ISSUE TITLE
打卡报错

### ISSUE THREAD

**Issue by zafirshi** [zju-health-report/zju-health-report-action-demo#2]
手动打卡后，手动运行workflow报错，错误信息如下

```
Run zju-health-report/action@release
  with:
    username: ***
    password: ***
*** 登陆成功！

/home/runner/work/_actions/zju-health-report/action/release/api.ts:65
  if (errMsg) throw new Error(`打卡提交失败：${errMsg}
                    ^
Error: 打卡提交失败：Unexpected token p in JSON at position 0

将环境变量 NODE_ENV 设置为 development 可以获得 oldInfo 的详细信息，请参考官方文档: https://github.com/zju-health-report/action#%E5%91%BD%E4%BB%A4%E[8](https://github.com/zafirshi/zju-health-report-action-demo/runs/5800565896?check_suite_focus=true#step:2:8)%A1%8C-cli

    at submit (/home/runner/work/_actions/zju-health-report/action/release/api.ts:65:21)
    at processTicksAndRejections (node:internal/process/task_queues:[9](https://github.com/zafirshi/zju-health-report-action-demo/runs/5800565896?check_suite_focus=true#step:2:9)6:5)
    at Object.runZjuHealthReport (/home/runner/work/_actions/zju-health-report/action/release/api.ts:98:5)
```

**Comment by zafirshi** [comment]
抱歉！因能力和系统限制，我这边无法复现这个错误，只在GitHub Action中出现

**Comment by LukeLIN-web** [comment]
这是因为如果打卡过就抛出error把， 其实应该打卡过就忽略？

**Comment by LukeLIN-web** [comment]
For security reasons, you cannot change the visibility of a fork. 不能变成private的

**Comment by LukeLIN-web** [comment]
Run zju-health-report/action@release
*** 登陆成功！



将环境变量 NODE_ENV 设置为 development 可以获得 oldInfo 的详细信息，请参考官方文档: https://github.com/zju-health-report/action#报告问题

请附上脱敏后的 oldInfo 前往 GitHub 提交 issue: https://github.com/zju-health-report/action/issues/new

    at submit (/home/runner/work/_actions/zju-health-report/action/release/api.ts:71:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:[5](https://github.com/LukeLIN-web/zju-health-report-action-demo/runs/5826774574?check_suite_focus=true#step:2:5))
    at Object.runZjuHealthReport (/home/runner/work/_actions/zju-health-report/action/release/api.ts:10[6](https://github.com/LukeLIN-web/zju-health-report-action-demo/runs/5826774574?check_suite_focus=true#step:2:6):5)

**Comment by zafirshi** [comment]
> @zafirshi
> 
> > 能力和系统限制
> 
> 具体是什么限制？本地打卡可以成功，github上就不行是嘛？
> 
> GitHub Action 也可以设置环境变量，但是 GitHub Action 的 log 是公开的，不要在公有仓库里面跑，不然别人会看到你的定位信息。只需要这样修改 GitHub Action:
> 
> ```yaml
>     steps:
>       - name: 打卡
>         uses: zju-health-report/action@release
>         with:
>           username: ${{ secrets[matrix.username] }}
>           password: ${{ secrets[matrix.password] }}
>         env:
>           NODE_ENV: development
> ```

感谢您的指导，刚在private仓库action里用development测试，发现是自己这边之前提交的打卡list缺少信息（学校的问卷更新了一些问题），但很奇怪，没有填写新增问题的schedule action依旧有两次是成功的，相信手动填写过之后是没有问题的

有一些建议：
您能否像之前一样新增钉钉机器人打卡状态提醒的特性，这样不用去手动查看action运行结果，最近一天未打卡蓝码就失效了
